name: Build RISC-V GNU Toolchain (MSYS2/Windows)

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 配置MSYS2并装所有依赖包
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gdb
            mingw-w64-x86_64-mpfr
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-libmpc
            mingw-w64-x86_64-zlib
            bison
            flex
            make
            texinfo

      # 2. 拉取源码 + 编译
      - name: Build riscv-gnu-toolchain
        shell: msys2 {0}
        run: |
          git clone https://github.com/riscv-collab/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          ./configure --with-arch=rv32gc --with-abi=ilp32 \
            --prefix=$PWD/../riscv-rv32 \
            --with-multilib-generator="rv32imac-ilp32--zicsr*zifencei*zaamo*zalrsc;rv32imafc-ilp32f--zicsr*zifencei*zaamo*zalrsc"
          make -j4
          cd ..
          ls -l ./riscv-rv32/bin || true

      # 3. 可选：打包产物供CI下载（zip）
      - name: Archive Toolchain
        if: always()
        run: |
          powershell Compress-Archive -Path riscv-rv32\* -DestinationPath riscv-rv32.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv-rv32-toolchain
          path: riscv-rv32.zip

